# Generated by Django 3.2 on 2021-12-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('orders', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='描述信息')),
                ('leader', models.CharField(max_length=255, verbose_name='部门负责人')),
                ('num', models.IntegerField(default=0, verbose_name='部门人数')),
                ('addr', models.TextField(verbose_name='部门地址')),
                ('phone', models.CharField(max_length=15, verbose_name='部门电话')),
            ],
            options={
                'verbose_name': '部门信息表',
                'verbose_name_plural': '部门信息表',
                'db_table': 'exam_department',
            },
        ),
    ]
