# Generated by Django 3.2 on 2021-12-22 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.CASCADE, related_name='department',
                                    to=settings.AUTH_USER_MODEL, verbose_name='部门员工'),
        ),
    ]
