name: Docker Image CI 

on: [push] 

jobs:

  build: 
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image 
      run: |
        docker login --username=${{ secrets.ACR_USERNAME }} registry.cn-beijing.aliyuncs.com --password=${{ secrets.ACR_PASSWORD }}
        docker build -t gayking:latest . 
        docker tag gayking registry.cn-beijing.aliyuncs.com/test_actions/uwsgi:latest
        docker push registry.cn-beijing.aliyuncs.com/test_actions/uwsgi:latest